apiVersion: node.k8s.io/v1
kind: RuntimeClass
metadata:
  name: crun
handler: crun
---
apiVersion: batch/v1
kind: Job
metadata:
  creationTimestamp: null
  name: wasm-demo
spec:
  template:
    metadata:
      annotations:
        module.wasm.image/variant: compat-smart
      creationTimestamp: null
    spec:
      containers:
      - image: wasmedge/example-wasi:latest
        name: wasm-demo
        resources: {}
        command: ["/wasi_example_main.wasm", "50000000"]
      restartPolicy: Never
      runtimeClassName: crun
  backoffLimit: 1