name: Containerd test

concurrency:
  group: containerd-${{ github.head_ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'info'
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: "0 0 */1 * *"

jobs:
  containerd:
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: "WasmEdge latest release, Crun master"
            latest: true
            wasmedge: ""
            crun: ""
            tag: "latest"
            variant: "compat-smart"
          - name: "WasmEdge 0.9.1, Crun 1.4.5"
            latest: false
            wasmedge: "0.9.1"
            crun: "1.4.5"
            tag: "compat"
            variant: "compat"
          - name: "WasmEdge 0.10.0, Crun 1.5"
            latest: false
            wasmedge: "0.10.0"
            crun: "1.5"
            tag: "latest"
            variant: "compat-smart"
          - name: "WasmEdge 0.11.2, Crun 1.6"
            latest: false
            wasmedge: "0.11.2"
            crun: "1.6"
            tag: "latest"
            variant: "compat-smart"
          - name: "WasmEdge 0.11.2, Crun 1.7"
            latest: false
            wasmedge: "0.11.2"
            crun: "1.7"
            tag: "latest"
            variant: "compat-smart"
          - name: "WasmEdge 0.11.2, Crun 1.7.1"
            latest: false
            wasmedge: "0.11.2"
            crun: "1.7.1"
            tag: "latest"
            variant: "compat-smart"
          - name: "WasmEdge 0.11.2, Crun 1.7.2"
            latest: false
            wasmedge: "0.11.2"
            crun: "1.7.2"
            tag: "latest"
            variant: "compat-smart"
    runs-on: ubuntu-20.04
    name: ${{ matrix.name }}

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install apt-get packages
        run: |
          sudo ACCEPT_EULA=Y apt-get update
          sudo ACCEPT_EULA=Y apt-get upgrade
          sudo ACCEPT_EULA=Y apt-get install git wget

      - name: Install containerd and crun (specified version)
        if: ${{ ! matrix.latest }}
        env:
          WASMEDGE_VERSION: ${{ matrix.wasmedge }}
          CRUN_VERSION: ${{ matrix.crun }}
        run: |
          bash containerd/install.sh --wasmedge=$WASMEDGE_VERSION --crun=$CRUN_VERSION

      - name: Install containerd and crun (latest version)
        if: ${{ matrix.latest }}
        run: |
          bash containerd/install.sh

      - name: Run demo in containerd
        env:
          TAG: ${{ matrix.tag }}
          VARIANT: ${{ matrix.variant }}
        run: |
          bash containerd/simple_wasi_application.sh --tag=$TAG --variant=$VARIANT > dump.log 2>&1

      - name: Display crun and wasmedge version
        run: |
          crun --version
          wasmedge --version

      - name: Dump the log of execution
        run: |
          cat dump.log

      - name: Check the result
        run: |
          if grep -q "Printed from wasi: This is from a main function" dump.log; then
            echo -e "Execution Success!"
          else
            echo -e "Execution Fail! Please check the above log for details"
            exit 1
          fi
