name: CRI-O test

concurrency:
  group: crio-${{ github.head_ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'info'
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: "0 0 */1 * *"

jobs:
  crio:
    strategy:
      fail-fast: false
      matrix:
        crun: ["1.6", "1.7", "1.7.1", "1.7.2"]
        wasmedge: ["0.11.0", "0.11.1", "0.11.2"]
        config: ["container_wasi.json"]
        tag: ["latest"]
        latest: [false]
        include:
          - name: "WasmEdge latest release, Crun master"
            latest: true
            wasmedge: "latest"
            crun: "latest"
            tag: "latest"
            config: "container_wasi.json"
        exclude:
          - crun: "1.7.1" # 1.7.1 introduce the new apparmor setting which will fail wasm custom handler
            wasmedge: "0.11.0"
          - crun: "1.7.1" # 1.7.1 introduce the new apparmor setting which will fail wasm custom handler
            wasmedge: "0.11.1"
          - crun: "1.7.1" # 1.7.1 introduce the new apparmor setting which will fail wasm custom handler
            wasmedge: "0.11.2"
          - crun: "1.7.2" # 1.7.2 introduce the new apparmor setting which will fail wasm custom handler
            wasmedge: "0.11.0"
          - crun: "1.7.2" # 1.7.2 introduce the new apparmor setting which will fail wasm custom handler
            wasmedge: "0.11.1"
          - crun: "1.7.2" # 1.7.2 introduce the new apparmor setting which will fail wasm custom handler
            wasmedge: "0.11.2"
    runs-on: ubuntu-20.04
    name: WasmEdge:${{ matrix.wasmedge }},crun:${{ matrix.crun }}

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install apt-get packages
        run: |
          sudo ACCEPT_EULA=Y apt-get update
          sudo ACCEPT_EULA=Y apt-get upgrade
          sudo ACCEPT_EULA=Y apt-get install git wget

      - name: Install CRI-O and crun (specified version)
        if: ${{ ! matrix.latest }}
        env:
          WASMEDGE_VERSION: ${{ matrix.wasmedge }}
          CRUN_VERSION: ${{ matrix.crun }}
        run: |
          bash crio/install.sh --wasmedge=$WASMEDGE_VERSION --crun=$CRUN_VERSION

      - name: Install CRI-O and crun (latest version)
        if: ${{ matrix.latest }}
        run: |
          bash crio/install.sh

      - name: Run demo in CRI-O
        env:
          TAG: ${{ matrix.tag }}
          CONFIG: ${{ matrix.config }}
        run: |
          bash crio/simple_wasi_application.sh --tag=$TAG --config=$CONFIG > dump.log 2>&1

      - name: Display crun and wasmedge version
        run: |
          crun --version
          wasmedge --version

      - name: Dump the log of execution
        run: |
          cat dump.log

      - name: Check the result
        run: |
          if grep -q "Printed from wasi: This is from a main function" dump.log; then
            echo -e "Execution Success!"
          else
            echo -e "Execution Fail! Please check the above log for details"
            exit 1
          fi
