name: k8s containerd test

concurrency:
  group: k8s-containerd-${{ github.head_ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'info'
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: "0 0 */1 * *"

jobs:
  k8s_containerd:
    strategy:
      fail-fast: false
      matrix:
        crun: ["1.5", "1.6", "1.7", "1.7.1", "1.7.2"]
        wasmedge: ["0.10.0", "0.10.1", "0.11.0", "0.11.1", "0.11.2"]
        tag: ["latest"]
        latest: [false]
        variant: ["compat-smart"]
        include:
          - name: "WasmEdge latest release, Crun master"
            latest: true
            wasmedge: ""
            crun: ""
            tag: "latest"
            variant: "compat-smart"
        exclude:
          - crun: "1.5" # 1.5 uses libwasmedge.so, which is changed to libwasmedge.so.0 after WasmEdge 0.11.0 release
            wasmedge: "0.11.0"
          - crun: "1.5" # 1.5 uses libwasmedge.so, which is changed to libwasmedge.so.0 after WasmEdge 0.11.0 release
            wasmedge: "0.11.1"
          - crun: "1.5" # 1.5 uses libwasmedge.so, which is changed to libwasmedge.so.0 after WasmEdge 0.11.0 release
            wasmedge: "0.11.2"
          - crun: "1.6" # 1.6 uses libwasmedge.so.0, but WasmEdge provides libwasmedge.so before 0.11.0 release
            wasmedge: "0.10.0"
          - crun: "1.6" # 1.6 uses libwasmedge.so.0, but WasmEdge provides libwasmedge.so before 0.11.0 release
            wasmedge: "0.10.1"
          - crun: "1.7" # 1.7 uses libwasmedge.so.0, but WasmEdge provides libwasmedge.so before 0.11.0 release
            wasmedge: "0.10.0"
          - crun: "1.7" # 1.7 uses libwasmedge.so.0, but WasmEdge provides libwasmedge.so before 0.11.0 release
            wasmedge: "0.10.1"
          - crun: "1.7.1" # 1.7.1 uses libwasmedge.so.0, but WasmEdge provides libwasmedge.so before 0.11.0 release
            wasmedge: "0.10.0"
          - crun: "1.7.1" # 1.7.1 uses libwasmedge.so.0, but WasmEdge provides libwasmedge.so before 0.11.0 release
            wasmedge: "0.10.1"
          - crun: "1.7.1" # 1.7.1 introduce the new apparmor setting which will fail wasm custom handler
            wasmedge: "0.11.0"
          - crun: "1.7.1" # 1.7.1 introduce the new apparmor setting which will fail wasm custom handler
            wasmedge: "0.11.1"
          - crun: "1.7.1" # 1.7.1 introduce the new apparmor setting which will fail wasm custom handler
            wasmedge: "0.11.2"
          - crun: "1.7.2" # 1.7.2 uses libwasmedge.so.0, but WasmEdge provides libwasmedge.so before 0.11.0 release
            wasmedge: "0.10.0"
          - crun: "1.7.2" # 1.7.2 uses libwasmedge.so.0, but WasmEdge provides libwasmedge.so before 0.11.0 release
            wasmedge: "0.10.1"
          - crun: "1.7.2" # 1.7.2 introduce the new apparmor setting which will fail wasm custom handler
            wasmedge: "0.11.0"
          - crun: "1.7.2" # 1.7.2 introduce the new apparmor setting which will fail wasm custom handler
            wasmedge: "0.11.1"
          - crun: "1.7.2" # 1.7.2 introduce the new apparmor setting which will fail wasm custom handler
            wasmedge: "0.11.2"
    runs-on: ubuntu-20.04
    name: WasmEdge:${{ matrix.wasmedge }},crun:${{ matrix.crun }}

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install apt-get packages
        run: |
          sudo ACCEPT_EULA=Y apt-get update
          sudo ACCEPT_EULA=Y apt-get upgrade
          sudo ACCEPT_EULA=Y apt-get install git wget

      - name: Install containerd and crun (specified version)
        if: ${{ ! matrix.latest }}
        env:
          WASMEDGE_VERSION: ${{ matrix.wasmedge }}
          CRUN_VERSION: ${{ matrix.crun }}
        run: |
          bash containerd/install.sh --wasmedge=$WASMEDGE_VERSION --crun=$CRUN_VERSION

      - name: Install containerd and crun (latest version)
        if: ${{ matrix.latest }}
        run: |
          bash containerd/install.sh

      - name: Installing and starting k8s
        run: |
          bash kubernetes_containerd/install.sh > k8s.log 2>&1

      - name: Sleep for 1200s
        run: sleep 1200s
        shell: bash

      - name: Dump the log of k8s setup
        run: |
          cat k8s.log

      - name: Run WasmEdge in k8s
        env:
          TAG: ${{ matrix.tag }}
          VARIANT: ${{ matrix.variant }}
        run: |
          bash kubernetes_containerd/simple_wasi_application.sh --tag=$TAG --variant=$VARIANT > dump.log 2>&1

      - name: Display crun and wasmedge version
        run: |
          crun --version
          wasmedge --version

      - name: Dump the log of execution
        run: |
          cat dump.log

      - name: Check the result
        run: |
          if grep -q "Printed from wasi: This is from a main function" dump.log; then
            echo -e "Execution Success!"
          else
            echo -e "Execution Fail! Please check the above log for details"
            exit 1
          fi
