name: k8s kwasm test

concurrency:
  group: k8s-kwasm-${{ github.head_ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'info'
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: "0 0 */1 * *"

jobs:
  k8s_kwasm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: helm/kind-action@v1.4.0
      - run: |
          helm repo add kwasm http://kwasm.sh/kwasm-operator/
          helm repo update
          helm install -n kwasm --create-namespace kwasm kwasm/kwasm-operator
          kubectl annotate node --all kwasm.sh/kwasm-node=true
          kubectl apply -f kwasm/simple_wasi_application.yaml
          sleep 30
          kubectl logs job/wasm-demo